---
deployment:
  tasks:
    # Deploy Backend to api.vayutrenz.vayunexsolution.com
    - /bin/cp -Rf backend-new/. /home/vayunexs/api.vayutrenz.vayunexsolution.com/
    # Deploy Frontend Build to vayutrenz.vayunexsolution.com
    - /bin/cp -Rf frontend-new/dist/. /home/vayunexs/vayutrenz.vayunexsolution.com/

