---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vayunexs
    # Deploy Backend to api.vayutrenz.vayunexsolution.com
    - /bin/cp -Rf Ecommerce-project/backend-new/. $DEPLOYPATH/api.vayutrenz.vayunexsolution.com/
    # Deploy Frontend Build to vayutrenz.vayunexsolution.com
    - /bin/cp -Rf Ecommerce-project/frontend-new/dist/. $DEPLOYPATH/vayutrenz.vayunexsolution.com/
